### ISSUE TITLE
Callback(); error

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/brewformer#2]
When ever there is a change in value within the drop-down menus an error appears stating that callback() is not a function.  This error originates from materialize.js, however, it does not affect the overall functionality of the state/city selector.

**Comment by trystant** [comment]
This is still occurring I think. Would a screenshot help?

**Comment by ZaBAOW** [comment]
The drop down format of the state/city selector has been scrapped in place of the text input fields that exist on the current version of the site.  So there are no more callback() errors that exist.
