### ISSUE TITLE
Request Limit

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/brewformer#4]
I believe that i have hit the limit of request that i can make to the BATTUTA! api.  This means that im back to square one.  I believe that i'll have to resort to a text form instead.  However, this would allow me to use the materialize autofill feature now.

**Comment by ZaBAOW** [comment]
Ive created a branch for this new text input version of the state/city selection feature.  Ive also decided to attempt to implement the materialize autocomplete.

**Comment by trystant** [comment]
I think that this is no longer an issue, considering that you're no longer using BATTUTA

**Comment by ZaBAOW** [comment]
BATTUTA! is no longer a part of this code despite how convenient the api was, it had far too strict of limits.  Materialize autocorrect has been thrown out too in place of an error catch function and faith that the user can spell.
