### ISSUE TITLE
Sending requests as JSON

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/brewformer#5]
when i send a request to brewerydb's api, i am returned an error caused by the request response where the request includes ":" where the website would want "," to be.  While researching the issue, i found that i am sending the request as a JSONP and brewerydb is only compatible with JSON format.  The only way I've found so far to get around this problem is via php, which i have now knowledge of how to use.

**Comment by ZaBAOW** [comment]
added a function in the callback of the url that only returns true.  When i open the webpage I am presented with this error:

```
Failed to load http://api.brewerydb.com/v2/?&key=bb5091fd74b7944bb27ac0fd535524ef&callback=function%20(){%20%20%20%20return%20true;%20%20%20%20}?: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

**Comment by trystant** [comment]
I think you solved this, correct @ZaBAOW ?

**Comment by ZaBAOW** [comment]
I have successfully been able to receive information from brewerydb in a JSON format, via the help of a herokuapp proxy url, which circumvents the issue with CORS.
