### ISSUE TITLE
Add aria accessibility attributes to brewformer

### ISSUE THREAD

**Issue by trystant** [ZaBAOW/brewformer#6]
Brewformer could use aria attributes in order to make sure that it meets accessibility guidelines and so that valid and valuable information is provided to screenreaders.

**Comment by trystant** [comment]
We're going to have pull requests with code reviews for this issue. We're also going to introduce [Github Flow](https://guides.github.com/introduction/flow/) to the development process.

**Comment by ZaBAOW** [comment]
Violations found by aXe:
- Elements must have sufficient color contrast:
```
<label class="left-align active" for="region">Region</label>
```
- id attribute value must be unique
```
<div id="item-container" class="col-3"><span id="list-item">Cultivar</span></div>
```
- Form elements must have labels
```
<input type="text" id="Region" class="ac-appender">
```

**Comment by ZaBAOW** [comment]
The website has been tested via the aXe chrome extension application and has been approved as an accessible site... for now.
![untitled](https://user-images.githubusercontent.com/28902060/33517571-4138885a-d74c-11e7-9956-0152a3411648.png)

**Comment by ZaBAOW** [comment]
brewformer, presently, is completely aria compatible.
